"""Git in an issue's worktree. The card's work stays uncommitted until the resolution commits it at merge; the steps
commit nothing. What a pull brings in from main is committed as base (absorb_main). The two files setup copies in and
the files the Sierra SDK generates never count as changes."""
import json, os, subprocess, sys

SETUP_COPIES = (".composer/pnpm-lock.yaml", ".composer/.gitignore")
NO_HOOKS = ["-c", "core.hooksPath=/dev/null"]
GENERATED = "auto-generated by the Sierra SDK"
HERE = os.path.dirname(os.path.abspath(__file__))


class Refused(Exception):
    pass


def git(wt, *args, check=True):
    r = subprocess.run(["git", "-C", wt] + NO_HOOKS + list(args), capture_output=True, text=True, stdin=subprocess.DEVNULL)
    if check and r.returncode:
        raise RuntimeError(f"git {args[0]} failed: " + (r.stderr or r.stdout).strip()[-400:])
    return r.stdout


def setup_copy(path):
    return any(path == c or path.endswith("/" + c) for c in SETUP_COPIES)


def generated(wt, path):
    """A file the Sierra SDK writes on every build and pull: its header says so."""
    try:
        with open(os.path.join(wt, path), encoding="utf-8", errors="replace") as f:
            return GENERATED in f.read(400)
    except OSError:
        return False


def dirty(wt, keep_generated=False):
    """Tracked paths with uncommitted changes, staged or not, both sides of a rename; the setup copies left out, and
    the SDK's generated files unless keep_generated."""
    recs, out = git(wt, "status", "--porcelain=v1", "-z", "--untracked-files=no").split("\0"), []
    k = 0
    while k < len(recs):
        r = recs[k]
        k += 1
        if len(r) < 4:
            continue
        out.append(r[3:])
        if r[0] in "RC":
            out.append(recs[k])
            k += 1
    return [p for p in dict.fromkeys(out) if not setup_copy(p) and (keep_generated or not generated(wt, p))]


def untracked(wt):
    return {p for p in git(wt, "ls-files", "--others", "--exclude-standard", "-z").split("\0") if p}


def binding(pages, agent, n, agent_dir):
    """The issue workspace's url when the worktree's Ghostwriter is bound to it; Refused otherwise."""
    st = load(os.path.join(pages, "agents", agent, "setup", f"{n}.status.json"))
    want = st.get("workspace")
    bound = load(os.path.join(agent_dir, ".composer", "build", "workspace-meta.json")).get("targetUrl")
    if not want:
        raise Refused("the issue has no Studio workspace of its own: run setup first")
    if bound != want:
        raise Refused(f"Ghostwriter in the worktree is bound to {bound or 'nothing'}, not the issue workspace {want}")
    return want


def absorb_main(wt, composer_rel):
    """After a Ghostwriter pull: commit, as the branch's new base, each changed or new Studio file whose content is a
    version origin/main has had. Main's merges reach every workspace as they land, so a pull brings them in; what they
    change is base, not the card's work. Everything else stays uncommitted. The committed paths, [] when none."""
    git(wt, "fetch", "-q", "origin", "main", check=False)
    paths = [p for p in dirty(wt) if p.startswith(composer_rel + "/")]
    paths += sorted(p for p in untracked(wt) if p.startswith(composer_rel + "/") and not setup_copy(p))
    base = []
    for p in paths:
        blob = git(wt, "hash-object", "--", p).strip() if os.path.exists(os.path.join(wt, p)) else None
        seen = git(wt, "log", "-m", "--no-abbrev", "--raw", "--format=", "origin/main", "--", p, check=False)
        if blob and blob in {f for line in seen.splitlines() if line.startswith(":") for f in line.split()[2:4]}:
            base.append(p)
    if base:
        git(wt, "add", "--", *base)
        git(wt, "commit", "--quiet", "-m", "Main's changes that reached the workspace", "--", *base)
    return base


def load(path):
    try:
        return json.load(open(path, encoding="utf-8"))
    except (OSError, ValueError):
        return {}
