"""A step's commit in the issue's worktree, and the rewind before a step reruns.

Strategy and context end with one commit of what they changed, its message carrying the trailer `Step: <step> <n>`;
analysis changes no files and commits nothing. Before step k runs, the issue branch goes back to the commit before the
first step commit of k or a later step, so the step sees the tree it saw the first time. A worktree with uncommitted
tracked changes is refused instead, the files named; the two files setup copies in and the files the Sierra SDK
generates do not count, and the rewind restores the generated ones first. When the rewind drops
a context commit or anything under .composer/, the tree's Studio content goes to the issue's own workspace with
setup.py's Ghostwriter sequence, and only when Ghostwriter there is bound to that workspace."""
import json, os, subprocess, sys

ORDER = ("analysis", "strategy", "context")
COMMITS = ("strategy", "context")
SETUP_COPIES = (".composer/pnpm-lock.yaml", ".composer/.gitignore")
LABEL = {"strategy": "Sim strategy", "context": "Context edit"}
NO_HOOKS = ["-c", "core.hooksPath=/dev/null"]
GENERATED = "auto-generated by the Sierra SDK"
HERE = os.path.dirname(os.path.abspath(__file__))


class Refused(Exception):
    pass


def git(wt, *args, check=True):
    r = subprocess.run(["git", "-C", wt] + NO_HOOKS + list(args), capture_output=True, text=True, stdin=subprocess.DEVNULL)
    if check and r.returncode:
        raise RuntimeError(f"git {args[0]} failed: " + (r.stderr or r.stdout).strip()[-400:])
    return r.stdout


def setup_copy(path):
    return any(path == c or path.endswith("/" + c) for c in SETUP_COPIES)


def generated(wt, path):
    """A file the Sierra SDK writes on every build and pull: its header says so."""
    try:
        with open(os.path.join(wt, path), encoding="utf-8", errors="replace") as f:
            return GENERATED in f.read(400)
    except OSError:
        return False


def dirty(wt, keep_generated=False):
    """Tracked paths with uncommitted changes, staged or not, both sides of a rename; the setup copies left out, and
    the SDK's generated files unless keep_generated."""
    recs, out = git(wt, "status", "--porcelain=v1", "-z", "--untracked-files=no").split("\0"), []
    k = 0
    while k < len(recs):
        r = recs[k]
        k += 1
        if len(r) < 4:
            continue
        out.append(r[3:])
        if r[0] in "RC":
            out.append(recs[k])
            k += 1
    return [p for p in dict.fromkeys(out) if not setup_copy(p) and (keep_generated or not generated(wt, p))]


def refusal(wt):
    """Why a step cannot run in this worktree now, or None."""
    d = dirty(wt)
    if not d:
        return None
    return ("the worktree has uncommitted changes: " + ", ".join(d[:10]) + (f" and {len(d) - 10} more" if len(d) > 10 else "")
            + "; commit or drop them first")


def untracked(wt):
    return {p for p in git(wt, "ls-files", "--others", "--exclude-standard", "-z").split("\0") if p}


def history(wt, n, since=None, limit=400):
    """The branch's first-parent commits above since (the fork point), newest first: {hash, short, subject, step},
    step set when the commit carries `Step: <step> <n>`."""
    rng = [f"{since}..HEAD"] if since else [f"-{limit}", "HEAD"]
    out = git(wt, "log", "--first-parent", "--format=%H%x1f%h%x1f%s%x1f%(trailers:key=Step,valueonly)%x1d", *rng)
    commits = []
    for rec in out.split("\x1d"):
        parts = rec.strip("\n").split("\x1f")
        if len(parts) < 4:
            continue
        mine = [v.split()[0] for v in parts[3].splitlines() if v.split()[1:] == [str(n)] and v.split()[0] in COMMITS]
        commits.append({"hash": parts[0], "short": parts[1], "subject": parts[2], "step": mine[0] if mine else None})
    return commits


def plan(wt, n, step, since=None):
    """What a (re)run of step drops: {to, dropped, files, push}, or None when no step commit of step or a later one is
    on the branch. Refused on a dirty worktree."""
    why = refusal(wt)
    if why:
        raise Refused(why)
    commits = history(wt, n, since)
    k = ORDER.index(step)
    hits = [i for i, c in enumerate(commits) if c["step"] and ORDER.index(c["step"]) >= k]
    if not hits:
        return None
    oldest = hits[-1]
    target = git(wt, "rev-parse", commits[oldest]["hash"] + "^").strip()
    files = [f for f in git(wt, "diff", "--name-only", "-z", target, "HEAD").split("\0") if f]
    dropped = commits[:oldest + 1]
    push = any(c["step"] == "context" for c in dropped) or any(f.startswith(".composer/") or "/.composer/" in f for f in files)
    return {"from": commits[0]["hash"], "to": target, "dropped": [{k2: c[k2] for k2 in ("short", "subject", "step")} for c in dropped],
            "files": files, "push": push}


def binding(pages, agent, n, agent_dir):
    """The issue workspace's url when the worktree's Ghostwriter is bound to it; Refused otherwise."""
    st = load(os.path.join(pages, "agents", agent, "setup", f"{n}.status.json"))
    want = st.get("workspace")
    bound = load(os.path.join(agent_dir, ".composer", "build", "workspace-meta.json")).get("targetUrl")
    if not want:
        raise Refused("the issue has no Studio workspace of its own: run setup first")
    if bound != want:
        raise Refused(f"Ghostwriter in the worktree is bound to {bound or 'nothing'}, not the issue workspace {want}")
    return want


def reset(wt, target):
    gen = [p for p in dirty(wt, keep_generated=True) if generated(wt, p)]
    if gen:
        git(wt, "checkout", "--", *gen)
    git(wt, "reset", "--keep", target)


def push(sierra, agent_dir, wt, composer_rel, log_path):
    """setup.py's Ghostwriter sequence, each command's output appended to log_path; raises on the first failure."""
    sys.path.insert(0, HERE)
    import setup
    with open(log_path, "a", encoding="utf-8") as log:
        for title, cmd in setup.sync_sequence(sierra, agent_dir, wt, composer_rel):
            log.write(f"== {title}\n$ {' '.join(cmd)}\n")
            log.flush()
            r = subprocess.run(cmd, capture_output=True, text=True, stdin=subprocess.DEVNULL)
            log.write((r.stdout + r.stderr).strip() + "\n")
            if r.returncode:
                raise RuntimeError(f"{title} failed: " + (r.stdout + r.stderr).strip()[-400:])


def commit(wt, prefix, n, step, before):
    """Commit what the step changed: tracked changes and files it created (untracked now, not in before), the setup
    copies left out. {hash, short, subject, files}, or None when it changed nothing."""
    files = dirty(wt) + sorted(f for f in untracked(wt) - before if not setup_copy(f))
    if not files:
        return None
    git(wt, "add", "-A", "--", *files)
    subject = f"{LABEL[step]} for {prefix}-{n}"
    git(wt, "commit", "--quiet", "-m", f"{subject}\n\nStep: {step} {n}\n")
    h = git(wt, "rev-parse", "HEAD").strip()
    return {"hash": h, "short": h[:9], "subject": subject, "files": files}


def load(path):
    try:
        return json.load(open(path, encoding="utf-8"))
    except (OSError, ValueError):
        return {}
